AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application. This template is partially managed by
  Amazon.Lambda.Annotations (v1.3.0.0).
Parameters:
  FullAccessRoleArn:
    Type: String
    Description: ARN of the FullAccess IAM role
  AddBudgetForUserQueueArn:
    Type: String
    Description: ARN of the AddBudgetForUserQueue
  RemoveUserFromBudgetQueueArn:
    Type: String
    Description: ARN of the RemoveUserFromBudgetQueue
  Environment:
    Type: String
    Description: The deployment environment (dev, qa, prod)
    AllowedValues:
    - dev
    - qa
    - prod
    Default: qa
Resources:
  IdentityApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
        - http://localhost:5173
        - https://onyx.dbrdak.com
        AllowHeaders:
        - authorization
        - content-type
        - host
        AllowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        MaxAge: 600
        AllowCredentials: true
      DefaultRouteSettings:
        DetailedMetricsEnabled: true
      Auth:
        DefaultAuthorizer: LambdaAuthorizer
        Authorizers:
          LambdaAuthorizer:
            FunctionArn:
              Fn::GetAtt:
              - LambdaAuthorizer
              - Arn
            AuthorizerPayloadFormatVersion: '2.0'
            EnableSimpleResponses: true
            Identity:
              Headers:
              - authorization
    Metadata:
      SamResourceId: IdentityApi
  Login:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Login
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: Login
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Login_Generated::Login
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/login
            Method: POST
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  Register:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Register
      SyncedEvents:
      - RootPost
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: Register
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Register_Generated::Register
      Events:
        RootPost:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/register
            Method: POST
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  VerifyEmail:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: VerifyEmail
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: VerifyEmail
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_VerifyEmail_Generated::VerifyEmail
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/verify-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  ResendEmail:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ResendEmail
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: ResendEmail
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_ResendEmail_Generated::ResendEmail
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/resend-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  Refresh:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Refresh
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: Refresh
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_Refresh_Generated::Refresh
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/refresh
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  ForgotPassword:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: ForgotPassword
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: ForgotPassword
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_ForgotPassword_Generated::ForgotPassword
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/forgot-password/request
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  NewPassword:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: NewPassword
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: NewPassword
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_NewPassword_Generated::NewPassword
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/forgot-password/new
            Method: PUT
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  GetUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: GetUser
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: GetUser
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_GetUser_Generated::GetUser
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /api/v1/user
            Method: GET
            ApiId:
              Ref: IdentityApi
  UpdateUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: UpdateUser
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: UpdateUser
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_UpdateUser_Generated::UpdateUser
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user
            Method: PUT
            ApiId:
              Ref: IdentityApi
  RequestEmailChange:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RequestEmailChange
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: RequestEmailChange
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_RequestEmailChange_Generated::RequestEmailChange
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/change-email
            Method: PUT
            ApiId:
              Ref: IdentityApi
  Logout:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: Logout
      SyncedEvents:
      - RootPut
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: Logout
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_Logout_Generated::Logout
      Events:
        RootPut:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/logout
            Method: PUT
            ApiId:
              Ref: IdentityApi
  RemoveUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RemoveUser
      SyncedEvents:
      - RootDelete
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: RemoveUser
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_RemoveUser_Generated::RemoveUser
      Events:
        RootDelete:
          Type: HttpApi
          Properties:
            Path: /api/v1/user/remove
            Method: DELETE
            ApiId:
              Ref: IdentityApi
  AddBudgetIdForUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: AddBudgetIdForUser
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: AddBudgetIdForUser
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_AddBudgetIdForUser_Generated::AddBudgetIdForUser
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue:
              Ref: AddBudgetForUserQueueArn
  RemoveBudgetIdForUser:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: RemoveBudgetIdForUser
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: RemoveBudgetIdForUser
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.User.UserFunctions_RemoveBudgetIdForUser_Generated::RemoveBudgetIdForUser
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue:
              Ref: RemoveUserFromBudgetQueueArn
  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: LambdaAuthorizer
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: LambdaAuthorizer
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Access.AccessFunction_FunctionHandler_Generated::FunctionHandler
  GoogleLogin:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: GoogleLogin
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: GoogleLogin
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_GoogleLogin_Generated::GoogleLogin
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/google/login
            Method: GET
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
  GoogleCallback:
    Type: AWS::Serverless::Function
    Metadata:
      SamResourceId: GoogleCallback
      SyncedEvents:
      - RootGet
      Tool: Amazon.Lambda.Annotations
    Properties:
      FunctionName:
        Fn::Sub: GoogleCallback
      Runtime: dotnet8
      CodeUri: s3://onyx-default/484385fc98e70eac2220023e521c5786
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      Role:
        Ref: FullAccessRoleArn
      PackageType: Zip
      Handler: Identity.Functions::Identity.Functions.Functions.Auth.AuthFunctions_GoogleCallback_Generated::GoogleCallback
      Events:
        RootGet:
          Type: HttpApi
          Properties:
            Path: /api/v1/auth/google/callback
            Method: GET
            ApiId:
              Ref: IdentityApi
            Auth:
              Authorizer: NONE
Outputs:
  ApiURL:
    Description: API endpoint URL
    Value:
      Fn::Sub: https://${IdentityApi}.execute-api.${AWS::Region}.amazonaws.com/
  LambdaAuthorizerArn:
    Description: The ARN of the Lambda Authorizer
    Value:
      Fn::GetAtt:
      - LambdaAuthorizer
      - Arn
