AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  FullAccessRoleArn:
    Type: String
    Description: ARN of the FullAccess IAM role
Resources:
  SendEmail:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SendEmail

  EmailSender:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Messanger.Lambda::Messanger.Lambda.Functions.Emails.EmailLambda::FunctionHandler
      Runtime: dotnet8
      CodeUri: .
      FunctionName: EmailSender
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      PackageType: Zip
      Role: !Ref FullAccessRoleArn
      Environment:
        Variables:
          TopicArn: !Ref SendEmail
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic: !Ref SendEmail
Outputs:
  SendEmailTopicArn:
    Description: "The ARN of the Send Email Topic"
    Value: !GetAtt SendEmail.TopicArn