AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  FullAccessRoleArn:
    Type: String
    Description: ARN of the FullAccess IAM role
Resources:
  SendEmail:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: SendEmail
    Metadata:
      SamResourceId: SendEmail
  EmailSender:
    Type: AWS::Serverless::Function
    Properties:
      Handler: Messanger.Lambda::Messanger.Lambda.Functions.Emails.EmailLambda::FunctionHandler
      Runtime: dotnet8
      CodeUri: s3://onyx-default/6e57deb9ec09d8f5ba8c1ffe347c8f31
      FunctionName: EmailSender
      MemorySize: 3008
      EphemeralStorage:
        Size: 3008
      Timeout: 30
      PackageType: Zip
      Role:
        Ref: FullAccessRoleArn
      Events:
        SnsEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: SendEmail
    Metadata:
      SamResourceId: EmailSender
Outputs:
  SendEmailTopicName:
    Description: Send email topic name
    Value:
      Fn::GetAtt:
      - SendEmail
      - TopicName
