export const POPULAR_CURRENCY = [
  { label: "USD", value: "USD" },
  { label: "AUD", value: "AUD" },
  { label: "CAD", value: "CAD" },
  { label: "GBP", value: "GBP" },
  { label: "EUR", value: "EUR" },
  { label: "CHF", value: "CHF" },
  { label: "JPY", value: "JPY" },
  { label: "PLN", value: "PLN" },
] as const;

export const OTHER_CORRENCY = [
  { label: "THB", value: "THB" },
  { label: "HKD", value: "HKD" },
  { label: "NZD", value: "NZD" },
  { label: "SGD", value: "SGD" },
  { label: "HUF", value: "HUF" },
  { label: "UAH", value: "UAH" },
  { label: "CZK", value: "CZK" },
  { label: "DKK", value: "DKK" },
  { label: "ISK", value: "ISK" },
  { label: "NOK", value: "NOK" },
  { label: "SEK", value: "SEK" },
  { label: "RON", value: "RON" },
  { label: "BGN", value: "BGN" },
  { label: "TRY", value: "TRY" },
  { label: "ILS", value: "ILS" },
  { label: "CLP", value: "CLP" },
  { label: "PHP", value: "PHP" },
  { label: "MXN", value: "MXN" },
  { label: "ZAR", value: "ZAR" },
  { label: "BRL", value: "BRL" },
  { label: "MYR", value: "MYR" },
  { label: "IDR", value: "IDR" },
  { label: "INR", value: "INR" },
  { label: "KRW", value: "KRW" },
  { label: "CNY", value: "CNY" },
  { label: "XDR", value: "XDR" },
] as const;

export const ALL_CURRENCIES = [
  "USD",
  "AUD",
  "CAD",
  "GBP",
  "EUR",
  "CHF",
  "JPY",
  "PLN",
  "THB",
  "HKD",
  "NZD",
  "SGD",
  "HUF",
  "UAH",
  "CZK",
  "DKK",
  "ISK",
  "NOK",
  "SEK",
  "RON",
  "BGN",
  "TRY",
  "ILS",
  "CLP",
  "PHP",
  "MXN",
  "ZAR",
  "BRL",
  "MYR",
  "IDR",
  "INR",
  "KRW",
  "CNY",
  "XDR",
] as const;
