name: firebase_kurs
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.5.1
  firebase_ui_auth: ^1.13.1
  go_router: ^13.2.4
  uuid: ^4.4.0
  flutter_hooks: ^0.20.5
  adaptive_theme: ^3.6.0
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.0
  interpolate_animated: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
